#!/usr/bin/env node
require("https").get("https://ddragon.leagueoflegends.com/api/versions.json", res => {
  let body = "";
  res.on("data", chunk => body += chunk);
  res.on("end", () => {
    const versions = JSON.parse(body);
    const latest = versions[0];
    console.log(latest)
  });
});
