name: 每日检查 LOL 最新版本并及时更新

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build

      - name: Check if src/data.json is really changed
        run: |
          git diff --exit-code src/data.json || echo CHANGED=yes >> $GITHUB_ENV

      - name: check $CHANGED
        run: echo "CHANGED =" $CHANGED "."

      - name: Commit changes
        if: env.CHANGED == 'yes'
        uses: EndBug/add-and-commit@v4.4.0
        with:
          author_name: Xu Chunyang
          author_email: xuchunyang56@gmail.com
          message: Update lol version to latest
          add: src/data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        if: env.CHANGED == 'yes'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
